name: npb_polls
description: A polls service client for NPB standings.
version: 1.0.0
environment:
  sdk: '>=1.16.0 <2.0.0'
dependencies:
  angular2: 2.0.0-beta.17
  browser: ^0.10.0
  chartjs: ^0.2.0+1
  console_log_handler: ^0.2.1
  dart_to_js_script_rewriter: ^0.1.0
  http_lift:
    git:
     url: git://github.com/ntaoo/http_lift
     ref: master
#  http_lift:
#    path: ./../../http_lift
  js: ^0.6.0
  logging: ^0.11.3
  ng2_g_signin: ^0.2.0
  quiver: ^0.22.0
  sass: ^0.4.2
  stack_trace: ^1.6.5
  stream_transformers: ^0.3.0+3
  usage: ^2.2.2
dev_dependencies:
  test: ^0.12.13+4
  grinder: ^0.8.0+2
transformers:
- sass
- angular2:
    platform_directives:
    - 'package:angular2/common.dart#CORE_DIRECTIVES'
    - 'package:angular2/common.dart#FORM_DIRECTIVES'
    entry_points: web/main.dart
- dart_to_js_script_rewriter
- $dart2js:
    minify: true
    commandLineOptions:
    - --enable-experimental-mirrors
    - --trust-type-annotations
    - --trust-primitives
    - --show-package-warnings
